// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrsg3onzfD7EM5aVJtRJPqKVT_dt-wSjU',
    appId: '1:533006065088:web:2c33db6325105382bfbc25',
    messagingSenderId: '533006065088',
    projectId: 'goldmart-1e92c',
    authDomain: 'goldmart-1e92c.firebaseapp.com',
    storageBucket: 'goldmart-1e92c.appspot.com',
    measurementId: 'G-Z38VEZV7GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgAU_mZVACupVRb48zLYc1WLMny6DBvPM',
    appId: '1:533006065088:android:f1308b71d1b281aabfbc25',
    messagingSenderId: '533006065088',
    projectId: 'goldmart-1e92c',
    storageBucket: 'goldmart-1e92c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1s-4g-0zrHBCAGeCiDIz7BstngiwchMk',
    appId: '1:533006065088:ios:a4c02bd0cf6cb112bfbc25',
    messagingSenderId: '533006065088',
    projectId: 'goldmart-1e92c',
    storageBucket: 'goldmart-1e92c.appspot.com',
    iosBundleId: 'com.example.goldMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1s-4g-0zrHBCAGeCiDIz7BstngiwchMk',
    appId: '1:533006065088:ios:a4c02bd0cf6cb112bfbc25',
    messagingSenderId: '533006065088',
    projectId: 'goldmart-1e92c',
    storageBucket: 'goldmart-1e92c.appspot.com',
    iosBundleId: 'com.example.goldMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrsg3onzfD7EM5aVJtRJPqKVT_dt-wSjU',
    appId: '1:533006065088:web:24f03678d4af21cdbfbc25',
    messagingSenderId: '533006065088',
    projectId: 'goldmart-1e92c',
    authDomain: 'goldmart-1e92c.firebaseapp.com',
    storageBucket: 'goldmart-1e92c.appspot.com',
    measurementId: 'G-M4T9QNW3BC',
  );
}
